# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pbuf_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pbuf_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12pbuf_message.proto\"\x1a\n\x07Object2\x12\x0f\n\x07number2\x18\x01 \x01(\x03\"1\n\x06Object\x12\x0c\n\x04str2\x18\x01 \x01(\t\x12\x19\n\x07object2\x18\x02 \x01(\x0b\x32\x08.Object2\"\x8b\x01\n\x0fProtobufMessage\x12\x0e\n\x06number\x18\x01 \x01(\x03\x12\n\n\x02pi\x18\x02 \x01(\x01\x12\x0b\n\x03str\x18\x03 \x01(\t\x12\x10\n\x08null_key\x18\x04 \x01(\t\x12\x17\n\x06object\x18\x05 \x01(\x0b\x32\x07.Object\x12\x11\n\tnum_array\x18\x06 \x03(\x03\x12\x11\n\tstr_array\x18\x07 \x03(\tb\x06proto3')
)




_OBJECT2 = _descriptor.Descriptor(
  name='Object2',
  full_name='Object2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number2', full_name='Object2.number2', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=48,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str2', full_name='Object.str2', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object2', full_name='Object.object2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=99,
)


_PROTOBUFMESSAGE = _descriptor.Descriptor(
  name='ProtobufMessage',
  full_name='ProtobufMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='ProtobufMessage.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pi', full_name='ProtobufMessage.pi', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str', full_name='ProtobufMessage.str', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='null_key', full_name='ProtobufMessage.null_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='ProtobufMessage.object', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_array', full_name='ProtobufMessage.num_array', index=5,
      number=6, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='str_array', full_name='ProtobufMessage.str_array', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=241,
)

_OBJECT.fields_by_name['object2'].message_type = _OBJECT2
_PROTOBUFMESSAGE.fields_by_name['object'].message_type = _OBJECT
DESCRIPTOR.message_types_by_name['Object2'] = _OBJECT2
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['ProtobufMessage'] = _PROTOBUFMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Object2 = _reflection.GeneratedProtocolMessageType('Object2', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT2,
  '__module__' : 'pbuf_message_pb2'
  # @@protoc_insertion_point(class_scope:Object2)
  })
_sym_db.RegisterMessage(Object2)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'pbuf_message_pb2'
  # @@protoc_insertion_point(class_scope:Object)
  })
_sym_db.RegisterMessage(Object)

ProtobufMessage = _reflection.GeneratedProtocolMessageType('ProtobufMessage', (_message.Message,), {
  'DESCRIPTOR' : _PROTOBUFMESSAGE,
  '__module__' : 'pbuf_message_pb2'
  # @@protoc_insertion_point(class_scope:ProtobufMessage)
  })
_sym_db.RegisterMessage(ProtobufMessage)


# @@protoc_insertion_point(module_scope)
