# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14simple_message.proto\"-\n\x0e\x41notherMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05num64\x18\x02 \x01(\x03\"\xe2\x02\n\rSimpleMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05num64\x18\x02 \x01(\x03\x12\x0f\n\x07\x66loat64\x18\x03 \x01(\x01\x12\x0c\n\x04uuid\x18\x04 \x01(\x0c\x12!\n\x04type\x18\x05 \x01(\x0e\x32\x13.SimpleMessage.Type\x12\x11\n\tname_list\x18\x06 \x03(\t\x12\x12\n\nnum64_list\x18\x07 \x03(\x03\x12/\n\tmap_field\x18\x08 \x03(\x0b\x32\x1c.SimpleMessage.MapFieldEntry\x12$\n\x0b\x61nother_msg\x18\t \x01(\x0b\x32\x0f.AnotherMessage\x12%\n\x0c\x61nother_msg2\x18\n \x03(\x0b\x32\x0f.AnotherMessage\x1a/\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1c\n\x04Type\x12\x08\n\x04Ping\x10\x00\x12\n\n\x06Urgent\x10\x01\x62\x06proto3')
)



_SIMPLEMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='SimpleMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Ping', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Urgent', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=398,
  serialized_end=426,
)
_sym_db.RegisterEnumDescriptor(_SIMPLEMESSAGE_TYPE)


_ANOTHERMESSAGE = _descriptor.Descriptor(
  name='AnotherMessage',
  full_name='AnotherMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AnotherMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num64', full_name='AnotherMessage.num64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=69,
)


_SIMPLEMESSAGE_MAPFIELDENTRY = _descriptor.Descriptor(
  name='MapFieldEntry',
  full_name='SimpleMessage.MapFieldEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SimpleMessage.MapFieldEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SimpleMessage.MapFieldEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=396,
)

_SIMPLEMESSAGE = _descriptor.Descriptor(
  name='SimpleMessage',
  full_name='SimpleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SimpleMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num64', full_name='SimpleMessage.num64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float64', full_name='SimpleMessage.float64', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='SimpleMessage.uuid', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='SimpleMessage.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name_list', full_name='SimpleMessage.name_list', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num64_list', full_name='SimpleMessage.num64_list', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map_field', full_name='SimpleMessage.map_field', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='another_msg', full_name='SimpleMessage.another_msg', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='another_msg2', full_name='SimpleMessage.another_msg2', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SIMPLEMESSAGE_MAPFIELDENTRY, ],
  enum_types=[
    _SIMPLEMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=426,
)

_SIMPLEMESSAGE_MAPFIELDENTRY.containing_type = _SIMPLEMESSAGE
_SIMPLEMESSAGE.fields_by_name['type'].enum_type = _SIMPLEMESSAGE_TYPE
_SIMPLEMESSAGE.fields_by_name['map_field'].message_type = _SIMPLEMESSAGE_MAPFIELDENTRY
_SIMPLEMESSAGE.fields_by_name['another_msg'].message_type = _ANOTHERMESSAGE
_SIMPLEMESSAGE.fields_by_name['another_msg2'].message_type = _ANOTHERMESSAGE
_SIMPLEMESSAGE_TYPE.containing_type = _SIMPLEMESSAGE
DESCRIPTOR.message_types_by_name['AnotherMessage'] = _ANOTHERMESSAGE
DESCRIPTOR.message_types_by_name['SimpleMessage'] = _SIMPLEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnotherMessage = _reflection.GeneratedProtocolMessageType('AnotherMessage', (_message.Message,), {
  'DESCRIPTOR' : _ANOTHERMESSAGE,
  '__module__' : 'simple_message_pb2'
  # @@protoc_insertion_point(class_scope:AnotherMessage)
  })
_sym_db.RegisterMessage(AnotherMessage)

SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), {

  'MapFieldEntry' : _reflection.GeneratedProtocolMessageType('MapFieldEntry', (_message.Message,), {
    'DESCRIPTOR' : _SIMPLEMESSAGE_MAPFIELDENTRY,
    '__module__' : 'simple_message_pb2'
    # @@protoc_insertion_point(class_scope:SimpleMessage.MapFieldEntry)
    })
  ,
  'DESCRIPTOR' : _SIMPLEMESSAGE,
  '__module__' : 'simple_message_pb2'
  # @@protoc_insertion_point(class_scope:SimpleMessage)
  })
_sym_db.RegisterMessage(SimpleMessage)
_sym_db.RegisterMessage(SimpleMessage.MapFieldEntry)


_SIMPLEMESSAGE_MAPFIELDENTRY._options = None
# @@protoc_insertion_point(module_scope)
